INSERT IGNORE INTO CATEGORY (category_id, name) VALUES (1, "FOOD");
INSERT IGNORE INTO CATEGORY (category_id, name) VALUES (2, "HOBBY_SEISURE");
INSERT IGNORE INTO CATEGORY (category_id, name) VALUES (3, "FASHION_BEAUTY");
INSERT IGNORE INTO CATEGORY (category_id, name) VALUES (4, "TRANSPORTATION_AUTOMOBILE");